spring.application.name=sigeco
# --- Connexion à MySQL ---
spring.datasource.url=jdbc:mysql://localhost:3306/sigeco_stage
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- Serveur ---
server.port=8082

spring.jpa.open-in-view=false
